name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision
        pip install tqdm
        pip install torchsummary

    - name: Run training and tests
      run: |
        python main.py
        python -c "
        import torch
        from model import MNISTNet
       model = MNISTNet()
#        total_params = sum(p.numel() for p in model.parameters())
#        assert total_params < 20000, 'Total Parameter Count Test failed'
#       assert any(isinstance(layer, torch.nn.BatchNorm2d) for layer in model.modules()), 'Batch Normalization Test failed'
#       assert any(isinstance(layer, torch.nn.Dropout) for layer in model.modules()), 'DropOut Test failed'
#       assert any(isinstance(layer, (torch.nn.Linear, torch.nn.AdaptiveAvgPool2d)) for layer in model.modules()), 'Fully Connected Layer or GAP Test failed'
#       "
#    - name: Run model evaluation
#      run: |
#        python test.py
#        python -c "
#        import torch
#        from test import test_model
#        accuracy = test_model()
#        assert accuracy > 99.4, 'Test Accuracy Test failed'
#       "